### ISSUE TITLE
Freeze on frame

### ISSUE THREAD

**Issue by nagualcode** [adafruit/pi_hello_video#2]
hello_video freezes when playing longer h264 files

**Comment by tdicola** [comment]
Thanks for checking out the project!  Hrm interesting, our hello video fork is just a very small change to the code from the Pi foundation's examples here: https://github.com/raspberrypi/userland/tree/master/host_applications/linux/apps/hello_pi  We just pulled it out from the bundle of examples so it could build and install separately, and added a really basic loop option.  I think you'll want to raise issues about the actual video decoding on their repository since they're the most familiar with how it works.  Thanks again for checking out the project!

**Comment by nagualcode** [comment]
Hello, we fixed this changin timeout value, please update with source at the firmware repo ;)
